# fly.toml app configuration file generated for spot-rev on 2023-07-01T21:23:37+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "spot-rev"
primary_region = "lhr"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
